# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 439)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.verticalGroupBox.setGeometry(QtCore.QRect(0, 10, 321, 381))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalGroupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 8, 0, 1, 2)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 9, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setClearButtonEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 7, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 6, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalGroupBox1 = QtWidgets.QGroupBox(self.centralWidget)
        self.verticalGroupBox1.setEnabled(True)
        self.verticalGroupBox1.setGeometry(QtCore.QRect(320, 10, 286, 381))
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalGroupBox1)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.verticalGroupBox1)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalGroupBox1)
        self.lineEdit_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit_8.setAutoFillBackground(True)
        self.lineEdit_8.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.lineEdit_8.setCursorPosition(0)
        self.lineEdit_8.setDragEnabled(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_3.addWidget(self.lineEdit_8)
        self.textEdit = QtWidgets.QTextEdit(self.verticalGroupBox1)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 120))
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalGroupBox1)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.verticalGroupBox1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 1, 1, 1, 3)
        self.radioButton = QtWidgets.QRadioButton(self.verticalGroupBox1)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_3.addWidget(self.radioButton, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.verticalGroupBox1)
        self.spinBox.setEnabled(True)
        self.spinBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(99)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 1, 1, 3)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalGroupBox1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 390, 591, 20))
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.label_8.setBuddy(self.lineEdit_3)
        self.label_5.setBuddy(self.lineEdit_4)
        self.label_7.setBuddy(self.lineEdit_6)
        self.label_6.setBuddy(self.lineEdit_5)
        self.label_3.setBuddy(self.lineEdit)
        self.label_9.setBuddy(self.lineEdit_7)
        self.label_4.setBuddy(self.lineEdit_2)
        self.label_2.setBuddy(self.spinBox)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.lineEdit_3.redo)
        self.pushButton_3.clicked.connect(self.lineEdit_7.undo)
        self.spinBox.valueChanged['int'].connect(self.progressBar.setMaximum)
        self.lineEdit_8.editingFinished.connect(self.radioButton.click)
        self.pushButton_2.clicked.connect(self.progressBar.reset)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "ClientID"))
        self.pushButton.setText(_translate("MainWindow", "Client_ID生成"))
        self.pushButton_3.setText(_translate("MainWindow", "Token生成"))
        self.label_5.setText(_translate("MainWindow", "インスタンスURL"))
        self.label_7.setText(_translate("MainWindow", "Password"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "App名"))
        self.lineEdit_4.setText(_translate("MainWindow", "knzk.me"))
        self.label_9.setText(_translate("MainWindow", "Token"))
        self.label_4.setText(_translate("MainWindow", "URL"))
        self.lineEdit_2.setText(_translate("MainWindow", "https://knzk.me"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">連投君-β</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">投稿内容</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "連投回数"))
        self.comboBox.setItemText(0, _translate("MainWindow", "public"))
        self.comboBox.setItemText(1, _translate("MainWindow", "unlisted"))
        self.comboBox.setItemText(2, _translate("MainWindow", "private"))
        self.comboBox.setItemText(3, _translate("MainWindow", "direct"))
        self.radioButton.setText(_translate("MainWindow", "CW"))
        self.pushButton_2.setText(_translate("MainWindow", "トゥート！"))

